#!/bin/bash

# Variables
keyboard_layout="dk"
time_zone="America/Godthab"
root_password="c"
root_password_diff="d"

until [[ ${root_password} == ${root_password_diff} ]]; do
  printf "Enter root password:\n"
  read -s root_password
  printf "Enter root password again:\n"
  read -s root_password_diff
  if [[ $root_password_diff != $root_password ]]; then
    printf "Passwords do not match!\n"
  fi
done

echo "Enter hostname:"
read hostname

# Create partitions
parted --script /dev/sda \
mklabel gpt \
mkpart primary fat32 2MiB 130MiB \
set 1 esp on \
mkpart primary ext4 130MiB 100%

# Format partitions
mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

# Mount partitions
mount /dev/sda2 /mnt
mkdir /mnt/efi
mount /dev/sda1 /mnt/efi

# Install packages
pacstrap /mnt base linux-hardened linux-firmware nano networkmanager grub efibootmgr

# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

# System configuration
# 52-55: NTP enable, timezone symlink, set system timezone, synchronize hwclock
# 56-59: Uncomment en_US locale, locale generation, set LANG variable, set keyboard layout
# 60-61: Set hostname, add hosts
# 62-63: Enable DHCP, enable NetworkManager service
# 64: Set root password
# 65-66: Install GRUB, create GRUB configuration file

arch-chroot /mnt /bin/bash << EOF
timedatectl set-ntp true
ln -sf "/usr/share/zoneinfo/${time_zone}" "/etc/localtime"
timedatectl set-timezone "${time_zone}"
hwclock --systohc
sed -i "/#en_US.UTF-8 UTF-8/s|#||" /etc/locale.gen
locale-gen
printf "LANG=en_US.UTF-8\n" > /etc/locale.conf
printf "KEYMAP=${keyboard_layout}\n" > /etc/vconsole.conf
printf "${hostname}\n" > /etc/hostname
printf "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t${hostname}.localdomain\t${hostname}\n" >> /etc/hosts
printf "[main]\ndhcp=dhclient\n" > /etc/NetworkManager/conf.d/dhcp-client.conf
systemctl enable NetworkManager
printf "root:${root_password}\n" | chpasswd
grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
EOF
shutdown
